export enum Events {
    MESSAGE="MESSAGE",
    NEW_GROUP="NEW_GROUP",
    MESSAGE_SEEN="MESSAGE_SEEN",
    USER_TYPING="USER_TYPING",
    UNREAD_MESSAGE="UNREAD_MESSAGE",
    NEW_FRIEND_REQUEST="NEW_FRIEND_REQUEST",
    NEW_MEMBER_ADDED="NEW_MEMBER_ADDED",
    ONLINE="ONLINE",
    OFFLINE="OFFLINE",
    MESSAGE_EDIT="MESSAGE_EDIT",
    DELETE_CHAT="DELETE_CHAT",
    MEMBER_REMOVED="MEMBER_REMOVED",
}