export const notificationTitles = [
    "📩 Hanji bhai, message vi dekhlo!",
    "💬 Oye, tere liye naya message aya hai!",
    "📱 Veer, kidda phir? Message vi dekhleo!",
    "📨 Bhai, naya message tera intezar kar raha hai!",
    "📲 Paji, koi tujhe yaad kar raha hai!",
    "📥 Chak de phatte! Message aa gaya!",
    "🗨️ Sun yaar, naya message dekh le!",
    "📨 Arey veere, message dekhna na bhoolna!",
    "💌 Oho, tera message intezaar kar raha hai!",
    "📲 Oye hoye! Message aaya hai, jaldi dekh!",
    "📩 Veere, time milte hi message dekh le!",
    "🗨️ Bro, message check kar le jaldi!",
    "💬 Yaar, naya message aaya hai, dekh le!",
    "📥 Suno suno, tera message aa gaya!",
    "📲 Message time! Jaldi se check karo!",
    "Kya bolti public? Naya message aaya hai! 🎉",
    "Hello ji, message aa gaya hai, check kar lo! 📬",
    "Kya scene hai? Message padh lo! 🤓",
    "Arey bhai, kya chal raha hai? Message dekho! 👀",
    "Aa gaya na message, mast lag raha hai! 😄",
    "Aajao, kya kar rahe ho? Message padh lo! 📱",
    "Bhai, dekh le message, kaafi mast hai! 😎",
    "Yo! Message mila hai, enjoy kar! 🎊",
    "Kamaal ka message aaya hai, dekh ke maza aayega! 🤩",
    "Oye hoye! Message aa gaya, kya baat hai! 🙌",
    "Wassup! Naya message check kar lo! 📝",
    "Balle balle! Naya message, full-on fun hai! 💃",
    "Message aaya hai, mood bana lo! 🎶",
    "Wah wah! Message padh ke kya kehna hai! 😄",
    "Kya chal raha hai bhai? Message dekho! 👀",
    "Message ki toh baat hi alag hai, mast hai boss! 😁",
    "Message aaya hai, dil khush kar diya! 😊",
    "Aa gaya message, maze lo! 🥳",
    "Bhailog, message padh lo, mazaa aa jayega! 🤩",
    "Kaali gaadi chaidiyea, nava ghar chaidieya miljugaa! 🚗🏠",
    "Kaala phone chaidiyea, nava suit chaidieya miljugaa! 📱👔",
    "Kaali bike chaidiyea, nava style chaidieya miljugaa! 🏍️🕶️",
    "Kaali gaddi chaidiyea, nava chain chaidieya miljugaa! 🚘⛓️",
    "Kaali watch chaidiyea, nava swag chaidieya miljugaa! ⌚🕶️",
    "Kaali car chaidiyea, nava mood chaidieya miljugaa! 🚙🎉",
    "Kaala ride chaidiyea, nava vibe chaidieya miljugaa! 🏎️🎶",
    "Kaala dress chaidiyea, nava charm chaidieya miljugaa! 👗💫",
    "Kaali gaadi chaidiyea, nava trend chaidieya miljugaa! 🚗👑",
    "Kaali ride chaidiyea, nava swag chaidieya miljugaa! 🏎️🔥",
    "Garmi itni ho rahi hai, message hi dhek lo! 🌞🔥",
    "Garmi ka mahaul hai, thandak ke messages bhej do! 🥵❄️",
    "Garmi ki chutti hai, message kyun nahi bhej rahe ho? 🌡️📲",
    "Garmi se taras gaye hain, thandi baatein kar lo! 😓❄️",
    "Garmi ke mausam mein, chat ka maza hi alag hai! 🌡️💬",
    "Garmi ki raaton mein, chat ka asli maza hai! 🌙💬",
    "Garmi mein chat karo, thand lag jayegi! 🥵📱",
    "Garmi ki dhoop se bachao, chat ke saath masti mein kho jao! 🌞💬",
    "Garmi ka asar hai, chat ka craze hai! 🌡️💬",
    "Garmi ki tarah garam chat, kaafi refreshing hai! 🌞💬"
];
