export const notificationTitles = [
    "📩 You've got a new message! Ready for some chat-desi delight?",
    "💬 Ding! Your chat order is up! Check your new message.",
    "🗨️ Hot and fresh message just for you. Don't let it get cold!",
    "📲 Chat's ready! Someone's waiting for your reply.",
    "🎉 Chat like a boss! You’ve got a new message.",
    "📬 Special delivery! New message served hot.",
    "💌 Your chat buddy just sent you a message. Dive in!",
    "📥 Message alert! Your chat session just got spicier.",
    "📨 Guess what? A new message just arrived. Yum!",
    "📧 Chat feast! There's a new message on the menu.",
    "🗨️ New message alert! Fresh and crispy, just for you.",
    "📲 Ready for a chat binge? You've got a new message.",
    "💬 Hello there! You've got a piping hot message.",
    "📩 Someone sent you a message. Time for some chat-tastic fun!",
    "📥 Ding! A new message has just been delivered to your chat inbox.",
    "🗨️ Fresh chat served! You've got a new message.",
    "📬 Chat cravings? Your message is here.",
    "💌 Inbox special! New message waiting for your reply.",
    "🎉 Chat is calling! You've got a new message.",
    "📧 It's chat o'clock! Check out your new message.",
    "📲 Ready for some chat goodness? You've got a new message.",
    "🗨️ Your chat platter is ready! Fresh message just for you.",
    "💬 Chat feast alert! New message on your screen.",
    "📩 Yum! Fresh message delivered to your inbox.",
    "📥 Chat special! New message ready for your reply.",
    "🎉 Get ready to chat! New message just arrived.",
    "📨 Hot and ready! You've got a new message.",
    "💬 Chat bonanza! New message just for you.",
    "📧 Inbox delight! Your new message is here.",
    "📲 A new message is ready to chat with you!",
    "🗨️ Time for some chat fun! You've got a new message.",
    "💌 Chat cravings? Your new message has arrived.",
    "📩 Ready for some chat magic? New message is here.",
    "📥 Inbox refresh! You've got a new message.",
    "📨 Surprise! A new message is waiting for you.",
    "🎉 Chat time! You've got a fresh message.",
    "📬 Message alert! Someone's waiting for your reply.",
    "💬 Your chat buddy just dropped you a message. Check it out!",
    "🗨️ Inbox special! New message served hot and fresh.",
    "📲 Chat delight! You've got a new message.",
    "📧 Ready for some chat fun? New message is here.",
    "💌 Chat cravings satisfied! New message just arrived.",
    "📩 Inbox treat! You've got a new message.",
    "📥 Your chat is ready! New message waiting for you.",
    "🎉 Chat celebration! You've got a new message.",
    "📨 Fresh and tasty message delivered to your inbox.",
    "🤖 System hang ek message se! Check it out! 🖥️",
    "Sarkari naukari chaidiya? Miljugii! Message dhek lo. 📩📝",
    "💌 Vo toh bhav nahi de rahi, message hi dekh lo phir. 📩",
    "🚗 Navi gaadi chaidiya? Miljugii! Check your message now. 🚙",
    "😠 Momos? Yeh kya hove?? Daal roti na kahi jaa rahi",
    "☕ Dolly ki chai pilo or baatchit chalao",
    "🏞 Hello pans, mein Kashmir mein hun or baatchit chala raha hun",
    "🌟 Punnet superstar is calling you",
    "😨 Thappad se dar nahi lagta sahab, message se lagta hai. 📩",
    "😌 All is well! Naya message aa gaya hai. 💌",
    "🧂 Kya aapke toothpaste mein namak hai? Aapke inbox mein message hai? 📩",
    "💖 Pyar dosti hai, aur message bhi! 💬",
    "💊 Mujhe drugs mat do, mujhe message do! 📨",
    "🚗 Aaj mere paas gaadi hai, bangla hai, message hai. 📩💼",
    "😢 Pushpa, I hate tears! Chat karne se sab theek ho jayega. 💬",
    "🚀 Chak de phatte! Message aa gaya! 📩",
    "🌞 Garmi itni ho rahi hai, message hi dhek lo! 🔥",
    "Basanti, 🐕 in kutto ke samne chat mat karna!",
    "Subah utho😎, instagram chalao🤳🏻, maar khao 🖐🏻, sojao 😴",
    "Traffic mein phas gaye? Chat karke time pass karo! 🚗📲",
    "Life update😊: pagal ho chuka hun💀",
    "Dhek dhek dhek 🕵️‍♂️ kaise khush hora 😃",
    "Karu guddi laal? 😤",
    "Beimaan hain bada mausam, lekin baatchit nahi🥵",
    "Bhai meme banane se pet nahi bharta! 🎬🍔",
    "Kya purav jha ai hain ?? 🤔",
    "Asambhavvvv!!🫨😲🤯 Naye message aaya hai! 📩🎉",

];
